Simplify consumption of this image
ministryofjustice/docker-tomee pull request #6
Opened 2018-04-12 08:17 UTC by jabley

Reuse the CMD definition in the parent image. We do not think that
any consumers of this image should need to override it. The purpose of
this image is to run TomEE. TomEE is configured using the existing
environment variables defined in the standard Tomcat launcher script
`catalina.sh`. Configuring the dockerised version via environment
variables should also be the pattern.

Defines CATALINA_OPTS to configure a secure-by-default configuration,
listing assumptions.

Provides guidance on how consumers should customise it.

2018-04-16 06:43 UTC, TheGavlar commented on Dockerfile
> +ENV CATALINA_OPTS="\
This solution introduced some issues for the CI. 
In getting CCLF CI pipeline (which I determined to be more of a priority) this was not adopted in CCLF.

2018-04-16 06:47 UTC, TheGavlar reviewed
I'd like to understand this change and would appreciate a discussion. The Dockerfile change (CMD -> ENV CATALINA_OPTS....."  introduced an issue for the CCLF CI which was blocking it.   So we need to review CCLF Dockerfile/CI implementation

2018-04-27 08:50 UTC, v1-evansb requested changes

2018-04-27 08:50 UTC, v1-evansb commented on README.md
> +``` can then run it locally using:
Can you clean up this markdown please James?

2018-04-27 08:50 UTC, v1-evansb commented on README.md
> +
Can you add the new TOMCAT_CONNECTOR_SECURE property details here?

2018-04-27 08:50 UTC, v1-evansb commented on README.md
> +"
can you add connector.secure / TOMCAT_CONNECTOR_SECURE here?

2018-04-27 08:50 UTC, v1-evansb commented on README.md
> +    my/image
can you add `-e TOMCAT_CONNECTOR_SECURE=false` ?

2018-04-27 08:50 UTC, v1-evansb commented on README.md
> +    -e TOMCAT_CONNECTOR_PROXY_PORT=8080 `
tidy up this line ending please

2018-04-27 09:30 UTC, closed without merging

2018-04-27 09:30 UTC, jabley commented
This can be left for later on.

2018-04-27 10:08 UTC, v1-evansb commented
Can you please rebase this branch on to the HEAD of the trunk